import '@styles/normalize.scss';

export const metadata = {
	title: 'Morla | Interactive Strategies',
	description: 'Generated by Next.js'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body>{children}</body>
		</html>
	);
}
