import '@styles/normalize.scss';
import '@styles/main.scss';
import { Inter } from 'next/font/google';
import { previewData } from 'next/headers';
import PreviewAlertBanner from '@components/_helpers/PreviewAlertBanner';
import Header from '@blocks/Header/Header';
import { MainContent } from '@components/_layout/MainContent/MainContent';
import { PageContainer } from '@components/_layout/PageContainer/PageContainer';
import { Footer } from '@components/_blocks/Footer/Footer';
import DetailHero from '@components/_blocks/DetailHero/DetailHero';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Morla | Interactive Strategies',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang='en'
			className={inter.className}
		>
			<body>
				{previewData() && <PreviewAlertBanner />}
				<PageContainer>
					{/* @ts-expect-error Server Component */}
					<Header />
					<DetailHero />
					<MainContent>{children}</MainContent>
					<Footer />
				</PageContainer>
			</body>
		</html>
	);
}
